CWASP Razor Edition/Pages/Create.cshtml.cs
using CWASP_Razor_Edition.Models;
using Microsoft.ApplicationInsights.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.Scripting;
using Microsoft.Identity.Client;

namespace CWASP_Razor_Edition.Pages
{
    public class CreateModel(CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext context) : PageModel
    {
        [ViewData]
        public string? Message { get; set; }

        private readonly CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext _context = context;

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Ticket Ticket { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/
        public async Task<IActionResult> OnPostSubmit()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Ticket.Add(Ticket);
            await _context.SaveChangesAsync();
            
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostCheckDuplicates()
        {

            if (!ModelState.IsValid)
            {
                Message = "CAUTION: Ticket does not have required fields.";
                return Page();
            }

            var tickets = from t in _context.Ticket                                                         // get all tickets from database
                          select t;

            foreach (var t in tickets)                                                                      // compare new ticket "student name" and "loaneroto" values to all tickets in db
            {
                if (t.StudentName == Ticket.StudentName || t.LoanerOTO == Ticket.LoanerOTO)                 // if there is a match, return the partial view with the message
                {
                    Message = "CAUTION: Ticket OTO # or student Name already exists in database.";
                    return Page();
                };
            }

            Message = "No duplicates found.";
            return Page();
        }
    }
}

CWASP Razor Edition/Pages/Delete.cshtml.cs
using CWASP_Razor_Edition.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CWASP_Razor_Edition.Pages
{
    public class DeleteModel(CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext context) : PageModel
    {
        private readonly CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext _context = context;

        [BindProperty]
        public Ticket Ticket { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                // return NotFound();
                return RedirectToPage("./Error");
            }

            var ticket = await _context.Ticket.FirstOrDefaultAsync(m => m.Id == id);

            if (ticket == null)
            {
                // return NotFound();
                return RedirectToPage("./Error");
            }
            else
            {
                Ticket = ticket;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("./Error");
            }

            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket != null)
            {
                Ticket = ticket;
                _context.Ticket.Remove(Ticket);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

CWASP Razor Edition/Pages/Details.cshtml.cs
using CWASP_Razor_Edition.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CWASP_Razor_Edition.Pages
{
    public class DetailsModel(CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext context) : PageModel
    {
        private readonly CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext _context = context;

        public Ticket Ticket { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("./Error");
            }

            var ticket = await _context.Ticket.FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return RedirectToPage("./Error");
            }
            else
            {
                Ticket = ticket;
            }
            return Page();
        }
    }
}

CWASP Razor Edition/Pages/Edit.cshtml.cs
using CWASP_Razor_Edition.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CWASP_Razor_Edition.Pages
{
    public class EditModel(CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext context) : PageModel
    {
        [ViewData]
        public string? Message { get; set; }

        private readonly CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext _context = context;

        [BindProperty]
        public Ticket Ticket { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("./Error");
            }

            var ticket = await _context.Ticket.FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                // return NotFound();
                return RedirectToPage("./Error");
            }
            Ticket = ticket;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostSave()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Ticket).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TicketExists(Ticket.Id))
                {
                    // return NotFound();
                    return RedirectToPage("./Error");
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool TicketExists(int id)
        {
            return _context.Ticket.Any(e => e.Id == id);
        }

        public IActionResult OnPostCheckDuplicates()
        {

            if (!ModelState.IsValid)
            {
                Message = "CAUTION: Ticket does not have required fields.";
                return Page();
            }

            var tickets = from t in _context.Ticket                                                         // get all tickets from database
                          select t;

            foreach (var t in tickets)                                                                      // compare new ticket "student name" and "loaneroto" values to all tickets in db
            {
                if ((t.StudentName == Ticket.StudentName || t.LoanerOTO == Ticket.LoanerOTO) && (t.Id != Ticket.Id))                 // if there is a match, return the partial view with the message (ignoring self)
                {
                    Message = "CAUTION: Ticket OTO # or student Name already exists in database.";
                    return Page();
                };
            }

            Message = "No duplicates found.";
            return Page();
        }
    }
}

CWASP Razor Edition/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CWASP_Razor_Edition.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel(ILogger<ErrorModel> logger) : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

#pragma warning disable IDE0052 // Remove unread private members
        private readonly ILogger<ErrorModel> _logger = logger;
#pragma warning restore IDE0052 // Remove unread private members

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

CWASP Razor Edition/Pages/Index.cshtml.cs
using CWASP_Razor_Edition.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CWASP_Razor_Edition.Pages
{
    public class IndexModel(CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext context) : PageModel
    {
        private readonly CWASP_Razor_Edition.Data.CWASP_Razor_EditionContext _context = context;
        public IList<Ticket> Ticket { get; set; } = default!;

        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? SearchOTO { get; set; }

        public SelectList? Reason { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? TicketReason { get; set; }

        public IQueryable<Ticket> PopulateModelVariable()
        {
            var tickets = from m in _context.Ticket
                          select m;
            return tickets;
        }

        public IQueryable<Ticket> PrepareModel(IQueryable<Ticket> tickets)
        {
#pragma warning disable CS8602 // Dereference of a possibly null reference.
            if (!string.IsNullOrEmpty(SearchString))
            {
                tickets = tickets.Where(s => s.StudentName.Contains(SearchString));
            }

            if (!string.IsNullOrEmpty(SearchOTO))
            {
                tickets = tickets.Where(o => o.LoanerOTO.Contains(SearchOTO));
            }

            if (!string.IsNullOrEmpty(TicketReason))
            {
                tickets = tickets.Where(x => x.Reason.Equals(TicketReason));
            }
#pragma warning restore CS8602 // Dereference of a possibly null reference.

            return tickets;
        }

        public async Task OnGetAsync()
        {
            var tickets = PopulateModelVariable();

            // Use LINQ to get list of genres.
            IQueryable<string> reasonQuery = from m in _context.Ticket
                                             orderby m.Reason
                                             select m.Reason;

            tickets = PrepareModel(tickets);

            Reason = new SelectList(await reasonQuery.Distinct().ToListAsync());
            Ticket = await tickets.ToListAsync();
        }

        public async Task<PartialViewResult?> OnGetDataListPartial()
        {
            var tickets = PopulateModelVariable();

            // Use LINQ to get list of genres.
            IQueryable<string> reasonQuery = from m in _context.Ticket
                                             orderby m.Reason
                                             select m.Reason;

            tickets = PrepareModel(tickets);

            Reason = new SelectList(await reasonQuery.Distinct().ToListAsync());
            Ticket = await tickets.ToListAsync();

            if ((string.IsNullOrEmpty(SearchOTO)) && (string.IsNullOrEmpty(SearchOTO)) && (string.IsNullOrEmpty(TicketReason)))
            {
                return Partial("_DataList", Ticket);
            }

            return null;
        }
    }
}

CWASP Razor Edition/Pages/_DataList.cshtml.cs
using CWASP_Razor_Edition.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CWASP_Razor_Edition.Pages
{
#pragma warning disable IDE1006 // Naming Styles
    public class _DataListModel() : PageModel
#pragma warning restore IDE1006 // Naming Styles
    {
    }
}

CWASP Razor Edition/Pages/Create.cshtml
@page 
@model CWASP_Razor_Edition.Pages.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" id="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ticket.LoanerOTO" class="control-label"></label>
                <input asp-for="Ticket.LoanerOTO" class="form-control" />
                <span asp-validation-for="Ticket.LoanerOTO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.StudentName" class="control-label"></label>
                <input asp-for="Ticket.StudentName" class="form-control" />
                <span asp-validation-for="Ticket.StudentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.LogTime" class="control-label"></label>
                <input asp-for="Ticket.LogTime" class="form-control" />
                <span asp-validation-for="Ticket.LogTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Reason" class="control-label"></label>
                <select asp-for="Ticket.Reason">
                    <option value="Home">Home</option>
                    <option value="Repair">Repair</option>
                    <option value="Charge">Charge</option>
                    <option value="Lost">Lost</option>
                    <option value="Other">Other</option>
                </select>
                <span asp-validation-for="Ticket.Reason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Description" class="control-label"></label>
                <input asp-for="Ticket.Description" class="form-control" />
                <span asp-validation-for="Ticket.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <h6>@ViewData["Message"]</h6>
            </div>
            <div class="form-group">
                <input type="submit" id="createButton" value="Create" class="btn btn-primary" asp-page-handler="Submit" />
                <input type="submit" value="Check Duplicates" class="btn btn-primary" asp-page-handler="CheckDuplicates" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @*
        The following scripts send a request to the server to update all index views.
        They enable live-updating core functionality.
    *@

    <script type="text/javascript" src="~/js/signalr/dist/browser/signalr.js"></script>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () => {
            const connection = new signalR.HubConnectionBuilder()       // Create the SignalR Hub connection.
                .configureLogging(signalR.LogLevel.Information)
                .withUrl("/Hubs/controlHub")
                .build();

            document.getElementById("createButton").addEventListener("click", function (event) {
                connection.invoke("AllCall").catch(function (err) {     // Talk to server.
                    return console.error(err.toString());
                });
            });

            async function start() {
                try {
                    await connection.start();
                    console.log("SignalR connected.");
                } catch (err) {
                    console.log(err);
                    console.log("Retrying SignalR connection in 10 seconds...");
                    setTimeout(start, 10000);
                }
            };

            connection.onclose(async () => {
                await start();
            });

            start();
        });
    </script>

    <script>
        $(document).ready(function () {
            let msg = $("#Message").val();
            if (msg != undefined) {
                if (msg.length > 0) {
                    swal.fire(msg);
                };
            }
         });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CWASP Razor Edition/Pages/Delete.cshtml
@page
@model CWASP_Razor_Edition.Pages.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<div>
    <h4>Ticket @Model.Ticket.Id</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.LoanerOTO)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.LoanerOTO)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.StudentName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.StudentName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.LogTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.LogTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Reason)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Reason)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Description)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Ticket.Id" />
        <input type="submit" id="deleteButton" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

@section Scripts {
    @*
        The following scripts send a request to the server to update all index views.
        They enable live-updating core functionality.
    *@

    <script type="text/javascript" src="~/js/signalr/dist/browser/signalr.js"></script>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () => {
            const connection = new signalR.HubConnectionBuilder()       // Create the SignalR Hub connection.
                .configureLogging(signalR.LogLevel.Information)
                .withUrl("/Hubs/controlHub")
                .build();

            document.getElementById("deleteButton").addEventListener("click", function (event) {
                connection.invoke("AllCall").catch(function (err) {     // Talk to server.
                    return console.error(err.toString());
                });
            });

            async function start() {
                try {
                    await connection.start();
                    console.log("SignalR connected.");
                } catch (err) {
                    console.log(err);
                    console.log("Retrying SignalR connection in 10 seconds...");
                    setTimeout(start, 10000);
                }
            };

            connection.onclose(async () => {
                await start();
            });

            start();
        });
    </script>
}

CWASP Razor Edition/Pages/Details.cshtml
@page
@model CWASP_Razor_Edition.Pages.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Ticket @Model.Ticket.Id</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.LoanerOTO)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.LoanerOTO)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.StudentName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.StudentName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.LogTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.LogTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Reason)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Reason)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Ticket.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

CWASP Razor Edition/Pages/Edit.cshtml
@page
@model CWASP_Razor_Edition.Pages.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Ticket @Model.Ticket.Id</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Ticket.Id" />
            <div class="form-group">
                <label asp-for="Ticket.LoanerOTO" class="control-label"></label>
                <input asp-for="Ticket.LoanerOTO" class="form-control" />
                <span asp-validation-for="Ticket.LoanerOTO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.StudentName" class="control-label"></label>
                <input asp-for="Ticket.StudentName" class="form-control" />
                <span asp-validation-for="Ticket.StudentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.LogTime" class="control-label"></label>
                <input asp-for="Ticket.LogTime" class="form-control" />
                <span asp-validation-for="Ticket.LogTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Reason" class="control-label"></label>
                <select asp-for="Ticket.Reason">
                    <option value="Home">Home</option>
                    <option value="Repair">Repair</option>
                    <option value="Charge">Charge</option>
                    <option value="Lost">Lost</option>
                    <option value="Other">Other</option>
                </select>
                <span asp-validation-for="Ticket.Reason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Description" class="control-label"></label>
                <input asp-for="Ticket.Description" class="form-control" />
                <span asp-validation-for="Ticket.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <h6>@ViewData["Message"]</h6>
            </div>
            <div class="form-group">
                <input type="submit" id="editButton" value="Save" class="btn btn-primary" asp-page-handler="Save" />
                <input type="submit" value="Check Duplicates" class="btn btn-primary" asp-page-handler="CheckDuplicates" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @*
        The following scripts send a request to the server to update all index views.
        They enable live-updating core functionality.
    *@

    <script type="text/javascript" src="~/js/signalr/dist/browser/signalr.js"></script>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () => {
            const connection = new signalR.HubConnectionBuilder()       // Create the SignalR Hub connection.
                .configureLogging(signalR.LogLevel.Information)
                .withUrl("/Hubs/controlHub")
                .build();

            document.getElementById("editButton").addEventListener("click", function (event) {
                connection.invoke("AllCall").catch(function (err) {     // Talk to server.
                    return console.error(err.toString());
                });
            });

            async function start() {
                try {
                    await connection.start();
                    console.log("SignalR connected.");
                } catch (err) {
                    console.log(err);
                    console.log("Retrying SignalR connection in 10 seconds...");
                    setTimeout(start, 10000);
                }
            };

            connection.onclose(async () => {
                await start();
            });

            start();
        });
    </script>

    <script>
        $(document).ready(function () {
            let msg = $("#Message").val();
            if (msg.length > 0) {
                swal.fire(msg);
            })
        })
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CWASP Razor Edition/Pages/Index.cshtml
@page
@model CWASP_Razor_Edition.Pages.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>

<form>
    <p style="display:inline">
        OTO #: <input type="text" asp-for="SearchOTO" />
        Student Name: <input type="text" asp-for="SearchString"/>
        Reason:
        <select asp-for="TicketReason" asp-items="Model.Reason">
            <option value="">All</option>
        </select>
        <input type="submit" value="Filter" id="Filter" />
    </p>
</form>

<div id="grid">
    <!-- Render the table using a partial view -->
    <partial name="_DataList" model="@Model.Ticket" />
</div>
@section scripts {
    @*
        The following scripts send a request to the server to update all index views.
        They enable live-updating core functionality.
    *@

    <script type="text/javascript" src="~/js/signalr/dist/browser/signalr.js"></script>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () => {
            const connection = new signalR.HubConnectionBuilder()       // Create the SignalR Hub connection.
                .configureLogging(signalR.LogLevel.Information)
                .withUrl("/Hubs/controlHub")
                .build();

            function update() {
                console.log("SignalR recieved an update request.");
                $('#grid').load('/Index?handler=DataListPartial');      // Load the partial view by calling the DataListPartial page handler.
            }

            connection.on("UpdatePartialView", function () {            // Listen for the command to refresh the partial view.
                setTimeout(update, 2000)                                // TEMPFIX: wait 2 seconds to allow db queries to finish so changes are displayed.
            });

            async function start() {
                try {
                    await connection.start();
                    console.log("SignalR connected.");
                } catch (err) {
                    console.log(err);
                    console.log("Retrying SignalR connection in 10 seconds...");
                    setTimeout(start, 10000);
                }
            };

            connection.onclose(async () => {
                await start();
            });

            start();
        });
    </script>
}

CWASP Razor Edition/Pages/_DataList.cshtml
@using CWASP_Razor_Edition.Models
@model IList<Ticket>

<!-- Class reference: https://getbootstrap.com/docs/4.0/layout/grid/ -->
<div class="container" style="display: block; margin-block-start: 1em; margin-block-end: 1em;">
    <div class="row">
    @foreach (var item in Model)
        {
            <div class="col-lg-3 bg-secondary bg-opacity-10" style="display: block; margin-block-end: 2em; padding: inherit; margin-right: 1em; margin-left: 1em; text-indent: 0.5em;">
                <div style="background-color: rgb(49, 123, 209) !important; color: rgb(255, 255, 255) !important;">
                    <strong>@Html.DisplayFor(modelItem => item.LoanerOTO)</strong>
                </div>
                <div><i>Loaned to @Html.DisplayFor(modelItem => item.StudentName)</i></div>
                <div>@Html.DisplayFor(modelItem => item.LogTime)</div>
                <div>Reason: @Html.DisplayFor(modelItem => item.Reason)</div>
                <div class="form-group" style="margin-left: auto; margin-right: auto;">
                    <a asp-page="./Index" asp-route-id="@item.Id"><input type="submit" value="Admin" class="btn btn-warning" /></a>
                    <a asp-page="./Details" asp-route-id="@item.Id"><input type="submit" value="Details" class="btn btn-primary" /></a>
                    <a asp-page="./Edit" asp-route-id="@item.Id"><input type="submit" value="Edit" class="btn btn-primary" /></a>
                    <a asp-page="./Delete" asp-route-id="@item.Id"><input type="submit" value="Delete" class="btn btn-danger" /></a>
                </div>
            </div>
        }
    </div>
</div>